# mouse

MOUSE_BEFORE_DELAY = 0.1
MOUSE_AFTER_DELAY = 0.1
MOUSE_PRESS_TIME = 0.2
MOUSE_INTERVAL = 0.2

# keyboard
KEYBOARD_BEFORE_DELAY = 0.05
KEYBOARD_AFTER_DELAY = 0.05
KEYBOARD_PRESS_TIME = 0.15
KEYBOARD_INTERVAL = 0.1

# clipbaord
CLIPBOARD_CHARSET = 'gbk'

# window
WINDOW_TITLE = 'Program Manager'
WINDOW_MANAGE_TIMEOUT = 5
WINDOW_NEW_BUILD_TIMEOUT = 5


